import { tags as t } from '@codemirror/highlight';

export const tagTree = {
  'comment': {
    'lineComment': {},
    'blockComment': {},
    'docComment': {},
  },
  'name': {
    'variableName': {},
    'typeName': {
      'tagName': {},
    },
    'propertyName': {
      'attributeName': {},
    },
    'className': {},
    'labelName': {},
    'namespace': {},
    'macroName': {},
  },
  'literal': {
    'string': {
      'docString': {},
      'character': {},
      'attributeValue': {},
    },
    'number': {
      'interger': {},
      'float': {},
    },
    'bool': {},
    'regexp': {},
    'escape': {},
    'color': {},
    'url': {},
  },
  'keyword': {
    'self': {},
    'null': {},
    'atom': {},
    'unit': {},
    'modifier': {},
    'operatorKeyword': {},
    'controlKeyword': {},
    'definitionKeyword': {},
    'moduleKeyword': {},
  },
  'operator': {
    'derefOperator': {},
    'arithmeticOperator': {},
    'logicOperator': {},
    'bitwiseOperator': {},
    'compareOperator': {},
    'updateOperator': {},
    'definitionOperator': {},
    'typeOperator': {},
    'controlOperator': {},
  },
  'punctuation': {
    'separator': {},
    'bracket': {
      'angleBracket': {},
      'squareBracket': {},
      'paren': {},
      'brace': {},
    },
  },
  'content': {
    'heading': {
      'heading1': {},
      'heading2': {},
      'heading3': {},
      'heading4': {},
      'heading5': {},
      'heading6': {},
    },
    'contentSeparator': {},
    'list': {},
    'quote': {},
    'emphasis': {},
    'strong': {},
    'link': {},
    'monospace': {},
    'strikethrough': {},
  },
  'inserted': {},
  'deleted': {},
  'changed': {},
  'invalid': {},
  'meta': {
    'documentMeta': {},
    'annotation': {},
    'processingInstruction': {},
  },
};

export const tagMap = {
  'comment': t.comment,
  'lineComment': t.lineComment,
  'blockComment': t.blockComment,
  'docComment': t.docComment,
  'name': t.name,
  'variableName': t.variableName,
  'typeName': t.typeName,
  'tagName': t.tagName,
  'propertyName': t.propertyName,
  'attributeName': t.attributeName,
  'className': t.className,
  'labelName': t.labelName,
  'namespace': t.namespace,
  'macroName': t.macroName,
  'literal': t.literal,
  'string': t.string,
  'docString': t.docString,
  'character': t.character,
  'attributeValue': t.attributeValue,
  'number': t.number,
  'integer': t.integer,
  'float': t.float,
  'bool': t.bool,
  'regexp': t.regexp,
  'escape': t.escape,
  'color': t.color,
  'url': t.url,
  'keyword': t.keyword,
  'self': t.self,
  'null': t.null,
  'atom': t.atom,
  'unit': t.unit,
  'modifier': t.modifier,
  'operatorKeyword': t.operatorKeyword,
  'controlKeyword': t.controlKeyword,
  'definitionKeyword': t.definitionKeyword,
  'moduleKeyword': t.moduleKeyword,
  'operator': t.operator,
  'derefOperator': t.derefOperator,
  'arithmeticOperator': t.arithmeticOperator,
  'logicOperator': t.logicOperator,
  'bitwiseOperator': t.bitwiseOperator,
  'compareOperator': t.compareOperator,
  'updateOperator': t.updateOperator,
  'definitionOperator': t.definitionOperator,
  'typeOperator': t.typeOperator,
  'controlOperator': t.controlOperator,
  'punctuation': t.punctuation,
  'separator': t.separator,
  'bracket': t.bracket,
  'angleBracket': t.angleBracket,
  'squareBracket': t.squareBracket,
  'paren': t.paren,
  'brace': t.brace,
  'content': t.content,
  'heading': t.heading,
  'heading1': t.heading1,
  'heading2': t.heading2,
  'heading3': t.heading3,
  'heading4': t.heading4,
  'heading5': t.heading5,
  'heading6': t.heading6,
  'contentSeparator': t.contentSeparator,
  'list': t.list,
  'quote': t.quote,
  'emphasis': t.emphasis,
  'strong': t.strong,
  'link': t.link,
  'monospace': t.monospace,
  'strikethrough': t.strikethrough,
  'inserted': t.inserted,
  'deleted': t.deleted,
  'changed': t.changed,
  'invalid': t.invalid,
  'meta': t.meta,
  'documentMeta': t.documentMeta,
  'annotation': t.annotation,
  'processingInstruction': t.processingInstruction,
};
